#!/bin/sh

cd ..

VAR1="\"${PWD}\""
VAR2="/Users/jersonmendez"
# Check if var2 is substring of var1
# if [[ "$VAR1" == *"$VAR2"* ]]; then

if [[ "$VAR1" == *"$VAR2"* ]]; then
    echo "String contained."
    echo "Current directory: $VAR1"
else
    echo "String not contained."
fi

cd ~/smartrater

UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")
BASE=$(git merge-base @ "$UPSTREAM")

if [ $LOCAL = $REMOTE ]; then
    echo "Up-to-date"
elif [ $LOCAL = $BASE ]; then
    echo "Need to pull"
elif [ $REMOTE = $BASE ]; then
    echo "Need to push"
else
    echo "Diverged"
fi

cd /root/systemfiles

UPSTREAM=${1:-'@{u}'}
LOCAL=$(git rev-parse @)
REMOTE=$(git rev-parse "$UPSTREAM")
BASE=$(git merge-base @ "$UPSTREAM")

if [ $LOCAL = $REMOTE ]; then
    echo "Up-to-date"
elif [ $LOCAL = $BASE ]; then
    echo "Need to pull"
elif [ $REMOTE = $BASE ]; then
    echo "Need to push"
else
    echo "Diverged"
fi